#
# Module manifest for module 'BadCodeExamples'
#
# Generated by: Security Testing Team
#
# Generated on: 11/26/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'BadCodeExamples.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = 'a1b2c3d4-e5f6-7890-1234-567890abcdef'

# Author of this module
Author = 'Security Testing Team'

# Company or vendor of this module
CompanyName = 'AiCodeReview'

# Copyright statement for this module
Copyright = '(c) 2025 AiCodeReview. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Test module containing intentionally insecure code patterns for security scanner validation. Contains deliberately vulnerable code for testing only.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Invoke-UnsafeExpression',
    'Add-UnsafeType',
    'Start-VariableProcess',
    'Get-HardcodedPassword',
    'ConvertTo-InsecureString',
    'Connect-WithBadCredentials',
    'Write-CredentialToLog',
    'Get-WeakHash',
    'Protect-WithWeakEncryption',
    'Invoke-UnencryptedAuth',
    'Skip-CertificateValidation',
    'Get-InsecureWebContent',
    'Import-UntrustedData',
    'Get-UnsafeFileContent',
    'Invoke-EncodedCommand',
    'Use-HighEntropyString',
    'Invoke-DownloadAndExecute',
    'Disable-SecurityFeatures',
    'Disable-UAC',
    'Add-RegistryPersistence',
    'New-PersistentTask',
    'Invoke-WithEmptyCatch',
    'Get-WithoutCmdletBinding',
    'Set-GlobalVariable',
    'Delete-OldFiles',
    'Retrieve-Data',
    'Change-Settings',
    'Invoke-ReflectionLoading',
    'New-SuspiciousCOMObject',
    'Invoke-WMIExecution',
    'Disable-ScriptBlockLogging',
    'Invoke-AMSIBypass',
    'Test-LanguageModeBypass',
    'Invoke-PolicyBypass',
    'Invoke-ReflectiveInjection',
    'Invoke-ProcessInjection',
    'Invoke-SuspiciousWebRequest',
    'Invoke-KerberosAttack',
    'Clear-SecurityLogs',
    'Invoke-TokenManipulation',
    'Invoke-LOLBins',
    'Invoke-SuspiciousRemoting',
    'Invoke-UACBypass',
    'Get-ClipboardData',
    'Invoke-ScreenCapture',
    'Invoke-DNSTunneling',
    'Invoke-MultipleViolations'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Security', 'Testing', 'Scanner', 'Vulnerable', 'BadCode')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/raandree/AiCodeReview/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/raandree/AiCodeReview'

        # ReleaseNotes of this module
        ReleaseNotes = 'Version 1.1.0 (2025-11-25) - Added 20 new security rules for 2025 threat intelligence. Coverage for AMSI bypass, CLM bypass, reflective injection. Total 48 functions covering 45+ security rules.'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
